<<<<<<< HEAD
# Generated by Django 3.2.8 on 2021-10-29 23:45
=======
# Generated by Django 3.2.4 on 2021-10-29 23:01
>>>>>>> 606f317ab8ad4ac1d724b3b1410fa70043724c8e

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.IntegerField()),
                ('SKU', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BuysSubItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.IntegerField()),
                ('SKU', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.IntegerField()),
                ('DOB', models.DateField()),
                ('views', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Discount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PreordersSubItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.IntegerField()),
                ('SKU', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='SubOnlyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.IntegerField()),
                ('SubscriptionDate', models.DateField()),
=======
            name='Subcriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.IntegerField()),
                ('SubscriptionDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SubOnlyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.IntegerField()),
>>>>>>> 606f317ab8ad4ac1d724b3b1410fa70043724c8e
            ],
        ),
        migrations.CreateModel(
            name='WeeklyAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdID', models.IntegerField()),
                ('Week', models.DateField()),
                ('Content', models.TextField()),
                ('Lists', models.TextField()),
            ],
        ),
    ]
