# Generated by Django 3.2.4 on 2021-11-28 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user', unique=True)),
                ('DOB', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('Name', models.CharField(default='', max_length=100)),
                ('SKU', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Discount', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='SubOnlyItem',
            fields=[
                ('SKU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='db_app.item', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='db_app.customer', unique=True)),
                ('SubscriptionDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyAd',
            fields=[
                ('AdID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Week', models.DateField()),
                ('Content', models.TextField()),
                ('Lists', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_app.item')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='views',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_app.weeklyad'),
        ),
        migrations.CreateModel(
            name='Buys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_app.item', unique=True)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_app.customer', unique=True)),
            ],
            options={
                'unique_together': {('UserID', 'SKU')},
            },
        ),
        migrations.CreateModel(
            name='PreordersSubItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_app.subonlyitem', unique=True)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_app.subscriber', unique=True)),
            ],
            options={
                'unique_together': {('UserID', 'SKU')},
            },
        ),
        migrations.CreateModel(
            name='Preorders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_app.item', unique=True)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_app.subscriber', unique=True)),
            ],
            options={
                'unique_together': {('UserID', 'SKU')},
            },
        ),
        migrations.CreateModel(
            name='BuysSubItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_app.subonlyitem', unique=True)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_app.subscriber', unique=True)),
            ],
            options={
                'unique_together': {('UserID', 'SKU')},
            },
        ),
    ]
