# Generated by Django 3.2.4 on 2021-10-29 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subcriber',
            new_name='Subscriber',
        ),
    ]
