# Generated by Django 3.2.4 on 2021-11-30 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0002_alter_preorders_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buys',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_app.item'),
        ),
        migrations.AlterField(
            model_name='buys',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_app.customer'),
        ),
        migrations.AlterField(
            model_name='buyssubitem',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_app.subonlyitem'),
        ),
        migrations.AlterField(
            model_name='buyssubitem',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_app.subscriber'),
        ),
        migrations.AlterField(
            model_name='preorders',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_app.item'),
        ),
        migrations.AlterField(
            model_name='preorders',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_app.customer'),
        ),
        migrations.AlterField(
            model_name='preorderssubitem',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_app.subonlyitem'),
        ),
        migrations.AlterField(
            model_name='preorderssubitem',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_app.subscriber'),
        ),
    ]
